jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      run: ./gradlew build --no-daemon
name: Java CI with Gradle
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
