jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - continue-on-error: true
      run: git checkout ${{ github.ref_name }}
      working-directory: ./traccar-web
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      run: ./gradlew build
    - continue-on-error: true
      uses: actions/setup-node@v4
      with:
        cache: npm
        cache-dependency-path: traccar-web/package-lock.json
        node-version: 21
    - continue-on-error: true
      run: npm ci && npm run build
      working-directory: ./traccar-web
    - continue-on-error: true
      run: 'sudo dpkg --add-architecture i386

        sudo apt-get update

        sudo apt-get install libgcc-s1:i386 libstdc++6:i386

        sudo apt-get install innoextract makeself wine32 s3cmd

        '
    - continue-on-error: true
      name: Build installers
      run: 'wget -q http://files.jrsoftware.org/is/5/isetup-5.5.6.exe

        wget -q https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2+13/OpenJDK21U-jdk_x64_windows_hotspot_21.0.2_13.zip

        wget -q https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2+13/OpenJDK21U-jdk_x64_linux_hotspot_21.0.2_13.tar.gz

        wget -q https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2+13/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.2_13.tar.gz

        ./package.sh ${{ github.event.inputs.version }}

        '
      working-directory: ./setup
    - continue-on-error: true
      env:
        S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
        S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      name: Upload installers
      run: s3cmd --acl-public put traccar-*.zip s3://traccar/builds/ --host=nyc3.digitaloceanspaces.com
        --host-bucket=traccar --access_key="$S3_ACCESS_KEY" --secret_key="$S3_SECRET_KEY"
      working-directory: ./setup
name: Build Installers
on:
  repository_dispatch:
    types: trigger-ga___release.yml
